details:
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: stu
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4217
  files:
  - /home/naumenko/work/mirna/input/HI.3550.004.RPI3.R4217_R1.fastq.gz
  genome_build: soltub3
  metadata:
    batch: batch1
    phenotype: experiment
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: stu
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4215
  files:
  - /home/naumenko/work/mirna/input/HI.3550.004.RPI1.R4215_R1.fastq.gz
  genome_build: soltub3
  metadata:
    batch: batch1
    phenotype: control
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: stu
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4218
  files:
  - /home/naumenko/work/mirna/input/HI.3550.004.RPI4.R4218_R1.fastq.gz
  genome_build: soltub3
  metadata:
    batch: batch2
    phenotype: experiment
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: stu
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4216
  files:
  - /home/naumenko/work/mirna/input/HI.3550.004.RPI2.R4216_R1.fastq.gz
  genome_build: soltub3
  metadata:
    batch: batch2
    phenotype: control
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: stu
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4220
  files:
  - /home/naumenko/work/mirna/input/HI.3550.004.RPI6.R4220_R1.fastq.gz
  genome_build: soltub3
  metadata:
    batch: batch3
    phenotype: experiment
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: stu
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4219
  files:
  - /home/naumenko/work/mirna/input/HI.3550.004.RPI5.R4219_R1.fastq.gz
  genome_build: soltub3
  metadata:
    batch: batch3
    phenotype: control
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: stu
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4228
  files:
  - /home/naumenko/work/mirna/input/HI.3550.005.RPI41.R4228_R1.fastq.gz
  genome_build: soltub3
  metadata:
    batch: batch4
    phenotype: experiment
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: stu
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4226
  files:
  - /home/naumenko/work/mirna/input/HI.3550.005.RPI7.R4226_R1.fastq.gz
  genome_build: soltub3
  metadata:
    batch:
    - batch4
    - batch5
    phenotype: control
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: stu
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4230
  files:
  - /home/naumenko/work/mirna/input/HI.3550.005.RPI43.R4230_R1.fastq.gz
  genome_build: soltub3
  metadata:
    batch: batch5
    phenotype: experiment
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: gma
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4229
  files:
  - /home/naumenko/work/mirna/input/HI.3550.005.RPI42.R4229_R1.fastq.gz
  genome_build: glymax2
  metadata:
    batch: batch6
    phenotype: experiment
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: gma
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4227
  files:
  - /home/naumenko/work/mirna/input/HI.3550.005.RPI8.R4227_R1.fastq.gz
  genome_build: glymax2
  metadata:
    batch:
    - batch6
    - batch7
    phenotype: control
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGC
    aligner: star
    species: gma
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: R4231
  files:
  - /home/naumenko/work/mirna/input/HI.3550.005.RPI44.R4231_R1.fastq.gz
  genome_build: glymax2
  metadata:
    batch: batch7
    phenotype: experiment
fc_date: '2016-05-10'
fc_name: srna1
upload:
  dir: ../final
