details:
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T1R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T1R1.MPS12300453-E06.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch1
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T1R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T1R2.MPS12300453-F06.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch2
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T1R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T1R3.MPS12302114-F09.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch3
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T2R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T2R1.MPS12302118-D10.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch4
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T2R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T2R2.MPS12300453-H06.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch5
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T2R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T2R3.MPS12302118-F10.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch6
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T3R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T3R1.MPS12302118-G10.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch7
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T3R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T3R2.MPS12302118-H10.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch8
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T3R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T3R3.MPS12300333-A10.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch9
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T4R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T4R1.MPS12300333-B10.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch10
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T4R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T4R2.MPS12300333-C10.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch11
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 12T4R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/12T4R3.MPS12300333-D10.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch12
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T1R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T1R1.MPS12302118-A07.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch13
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T1R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T1R2.MPS12300453-A06.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch14
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T1R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T1R3.MPS12302118-C07.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch15
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T2R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T2R1.MPS12302118-D07.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch16
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T2R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T2R2.MPS12302118-E07.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch17
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T2R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T2R3.MPS12302114-C09.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch18
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T3R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T3R1.MPS12302118-G07.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch19
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T3R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T3R2.MPS12302118-H07.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch20
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T3R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T3R3.MPS12300333-A09.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch21
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T4R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T4R2.MPS12300333-C09.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch22
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 1T4R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/1T4R3.MPS12300333-D09.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch23
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T1R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T1R1.MPS12302118-E08.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch24
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T1R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T1R2.MPS12302118-F08.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch25
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T1R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T1R3.MPS12302118-G08.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch26
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T2R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T2R1.MPS12302118-H08.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch27
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T2R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T2R2.MPS12302118-A09.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch28
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T2R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T2R3.MPS12302118-B09.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch29
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T3R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T3R1.MPS12302118-C09.3550.2.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch30
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T3R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T3R2.MPS12302118-D09.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch31
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T3R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T3R3.MPS12300333-E09.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch32
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T4R1
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T4R1.MPS12300333-F09.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch33
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T4R2
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T4R2.MPS12302114-E09.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch34
- algorithm:
    adapters:
    - TGGAATTCTCGGGTGCCAAGG
    aligner: star
    species: ath
    tools_off:
    - seqcluster
  analysis: smallRNA-seq
  description: 6T4R3
  files:
  - /hpf/largeprojects/ccmbio/naumenko/mirna_athaliana/input/6T4R3.MPS12300333-H09.3550.3.single.fastq.gz
  genome_build: TAIR10
  metadata:
    batch: batch35
fc_date: '2016-05-10'
fc_name: srna1
upload:
  dir: ../final
